### ISSUE TITLE
RFC: Yarn vs NPM

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition_react#3]
Yarn or NPM? discuss.

**Comment by watsonarw** [comment]
From the student perspective, I think we should have a `./go` script that abstracts whichever we choose away. The student should be able to just run `./go start` or `./go test` and not worry about whether we're using yarn or NPM behind the scenes.

See: https://www.thoughtworks.com/insights/blog/praise-go-script-part-i

**Comment by raytung** [comment]
In my experience, `yarn` is quite a lot faster than `npm`. But that was before the latest `npm` came out so I don't know what's the actual difference now.

**Comment by aaron-m-edwards** [comment]
Good point about the go script. However we would still require them to install yarn globally before installing.

Just for ease of installation I would say for for npm

**Comment by raytung** [comment]
We run everything through Docker so we don't have to worry about `nvm`, `yarn`, or `npm` or whatever else 😄

**Comment by aaron-m-edwards** [comment]
Do we really expect the students to have/setup docker?

**Comment by adamhope** [comment]
I commented in another thread, Docker seemed like more hassle than it was worth last time we tried it.

I don't have a preference as I haven't tried Yarn. Whichever is least obtrusive for students and doesn't make things harder for Windows users.

**Comment by watsonarw** [comment]
Looks like we've decided (for now at least) that we'll go with NPM. For Docker conversation, see https://github.com/twlevelup/watch_edition_react/issues/5
